//
// Created by thedevmanek on 12/5/23.
//

#ifndef ASSISTIVE_SHOULDER_FIRMWARE_NIMBLE_BLE_CENT_H
#define ASSISTIVE_SHOULDER_FIRMWARE_NIMBLE_BLE_CENT_H
void init_ble();
#endif //ASSISTIVE_SHOULDER_FIRMWARE_NIMBLE_BLE_CENT_H
